
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mybozyryjekltdgdvots.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15Ym96eXJ5amVrbHRkZ2R2b3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDYzOTEsImV4cCI6MjA1OTU4MjM5MX0.OqIWE5gYJhKIveDWwHiAZa0-WR8YgzIfUSnXFDhusdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
